### ISSUE TITLE
Setup instructions 

### ISSUE THREAD

**Issue by chadepl** [msmathcomp/hyperbolic-tsne#2]
1. Which are the requirements + creation of the environment
2. Installation of HyperbolicTSNE (optional depending on how we setup the project)
3. Walk through running an experiment 
4. Further explanation of the structure of the repo and how to obtain the results reported in the paper

**Comment by msmathcomp** [comment]
We tested the setup instructions on all three operating systems, those work. Whether the scripts all work is another story, to be tested.
